// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceManagement.Infrastructure.DB;

#nullable disable

namespace HousingSocietyApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210064355_initial-migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HousingSocietyApi.DataModel.Tables.account_grp_mst", b =>
                {
                    b.Property<int>("agm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("agm_id"));

                    b.Property<string>("account_group_desc")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("account_group_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("account_head")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("printing_sr")
                        .HasColumnType("int");

                    b.HasKey("agm_id");

                    b.ToTable("account_grp_mst");
                });

            modelBuilder.Entity("HousingSocietyApi.DataModel.Tables.install_mst", b =>
                {
                    b.Property<int>("i_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("i_id"));

                    b.Property<string>("i_addr1")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("i_addr2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("i_city")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("i_contact_no_1")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("i_contact_no_2")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("i_dist")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("i_email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("i_name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("i_pin")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("i_region")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("i_type")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.HasKey("i_id");

                    b.ToTable("install_mst");
                });

            modelBuilder.Entity("HousingSocietyApi.DataModel.Tables.society_ms", b =>
                {
                    b.Property<int>("soc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("soc_id"));

                    b.Property<string>("First_adjust")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("accounting_start_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("advance_previous_Billing")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_Accounts")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_Billing")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_accessoriess")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_admins")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_gate_keeper_app")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_managerials")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_masters")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("allow_mobile_app")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("auditor_id")
                        .HasColumnType("int");

                    b.Property<int>("authorised_share_capital")
                        .HasColumnType("int");

                    b.Property<string>("auto_revision_of_bill_receipt")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("bill_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("bill_format")
                        .HasColumnType("int");

                    b.Property<int>("billing_report")
                        .HasColumnType("int");

                    b.Property<int>("billing_type")
                        .HasColumnType("int");

                    b.Property<int>("construction_cost")
                        .HasColumnType("int");

                    b.Property<int>("dealer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("grace_period")
                        .HasColumnType("int");

                    b.Property<int>("interest_base")
                        .HasColumnType("int");

                    b.Property<int>("interest_charge_from")
                        .HasColumnType("int");

                    b.Property<string>("merge_opening_balance_for_bill")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("merge_payments_voucher_no")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("merge_supp_and_reg_bill_no")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("no_of_members")
                        .HasColumnType("int");

                    b.Property<int>("no_of_shares")
                        .HasColumnType("int");

                    b.Property<int>("per_share_amt")
                        .HasColumnType("int");

                    b.Property<string>("print_dealer_info")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<int>("rate_of_interest")
                        .HasColumnType("int");

                    b.Property<string>("show_cr_bal")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("show_hide_receipts_in_bill")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("show_supp_bill_amount_in_reg_bill")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("show_zero_bal_head_in_bill")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("soc_active")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("soc_addr1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("soc_addr2")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("soc_city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("soc_dist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("soc_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("soc_pin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("soc_reg_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("society_emailid")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("society_gst_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("society_pan_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("society_phone_no")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("start_bill_no")
                        .HasColumnType("int");

                    b.Property<int>("start_contra_no")
                        .HasColumnType("int");

                    b.Property<int>("start_jv_no")
                        .HasColumnType("int");

                    b.Property<int>("start_receipt_no")
                        .HasColumnType("int");

                    b.Property<int>("start_supp_bill_no")
                        .HasColumnType("int");

                    b.Property<int>("start_voucher_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("trial_days_end_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("type_of_interest")
                        .HasColumnType("int");

                    b.Property<string>("user_type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("soc_id");

                    b.ToTable("society_mst");
                });
#pragma warning restore 612, 618
        }
    }
}
